### ISSUE TITLE
add TargetView Library 🎯

### ISSUE THREAD

**Issue by anastr** [JStumpp/awesome-android#117]
add [TargetView](https://github.com/anastr/SimpleTargetView) (Animation View) if interesting

**Comment by JStumpp** [comment]
Sorry, I think it is a bit too special for this list. Thanks for the suggestions.

**Comment by anastr** [comment]
I do not understand 😓
Do you mean you want general Library ?!

i am so sorry, but i didn't know that 😔

**Comment by JStumpp** [comment]
Sorry, I try to keep only libraries on this curated list that are useful for lots of people. I honor your effort for your library, but currently I do not see lots of use cases for it.
