### ISSUE TITLE
Date/time libs for Android

### ISSUE THREAD

**Issue by mortenholmgaard** [JStumpp/awesome-android#166]
Are there no good Date/Time libs for Android as an alternative to java Date?
I have looked through this and other Android Awesome lists and it is not there.

**Comment by bryant1410** [comment]
You could use a port of the Java 8 Time API, such as [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP) (which I strongly recommend).

**Comment by bryant1410** [comment]
But this seemed to be more like a SO question.

**Comment by mortenholmgaard** [comment]
I just expected there to be a Date/Time section in the awesome list, like on the iOS/swift lists.

**Comment by JStumpp** [comment]
Thanks for the suggestion. Date and Time libs are added now in: https://github.com/JStumpp/awesome-android/commit/d4ea123738d3c5616e57f824d1a865dbb45beeb1

**Comment by MenoData** [comment]
What about my library [Time4A](https://github.com/MenoData/Time4A) in this section? Highlights are good internationalization and more calendars.
