### ISSUE TITLE
gradle-kotlin-dsl-libs

### ISSUE THREAD

**Issue by jmfayard** [JStumpp/awesome-android#255]
FYI, I have launched this project:

gradle-kotlin-dsl-libs: painless gradle dependencies management 

https://github.com/jmfayard/gradle-ko…

**Comment by JStumpp** [comment]
Thanks, added in https://github.com/JStumpp/awesome-android/commit/a9f8fdd3e818f34962e55df9e1d10b84cd99f7ec
