### ISSUE TITLE
Project Starters

### ISSUE THREAD

**Issue by mustafakuloglu** [JStumpp/awesome-android#256]
Here is the two awesome project starter:

[MVP](https://github.com/general-mobile/kotlin-android-mvp-starter)

[MVVM](https://github.com/general-mobile/kotlin-android-mvvm-starter)

Would you please add this two tool.

**Comment by JStumpp** [comment]
Thanks, the Android Architecture Blueprints are in my opinion better starters:
https://github.com/JStumpp/awesome-android/blob/master/readme.md#code-examples
