### ISSUE TITLE
Add MaterialProgressBar

### ISSUE THREAD

**Issue by DreaminginCodeZH** [JStumpp/awesome-android#42]
Material design ProgressBar with consistent appearance.

[https://github.com/DreaminginCodeZH/MaterialProgressBar](https://github.com/DreaminginCodeZH/MaterialProgressBar)

![Screenshot](https://cloud.githubusercontent.com/assets/4469895/8049717/3acc0cbc-0e95-11e5-890b-3819b51f53bb.png)

**Comment by JStumpp** [comment]
Thanks, Added it here: https://github.com/JStumpp/awesome-android/commit/99f446578c8962e22952d9d276ccad9fe835bb72
