### ISSUE TITLE
New library suggestions

### ISSUE THREAD

**Issue by dkharrat** [JStumpp/awesome-android#62]
Would you please add the following two Android libraries:

* https://github.com/dkharrat/NexusDialog
  Allows you to easily and quickly create forms in Android with little code

* https://github.com/dkharrat/NexusData
  Core Data for Android

Thanks!

**Comment by JStumpp** [comment]
Thanks. Please do a pull request in the future. I added the libraries in https://github.com/JStumpp/awesome-android/commit/da404a95390e03a6aa439be675ed608a62113a1e.
