### ISSUE TITLE
Elastic Progress Bar "renew" - Request to add

### ISSUE THREAD

**Issue by michelelacorte** [JStumpp/awesome-android#71]
Hello guys, could you add Elastic Progress Bar to your project?

https://github.com/michelelacorte/ElasticProgressBar

![alt tag](https://raw.githubusercontent.com/Tibolte/ElasticDownload/master/success.gif)

**Comment by JStumpp** [comment]
Sure, added in: https://github.com/JStumpp/awesome-android/commit/235b6a3ccb94224a1c2c317feef8e0b1d901b933
